name: Update README with a CS Quote

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Computer Science Quote
        run: curl -s https://api.quotable.io/random?tags=technology | jq -r '"\(.content) - \(.author)"' > quote.txt

      - name: Update README
        run: |
          sed -i "/<!-- CS_QUOTE -->/c\ - 💡  Computer Science Quote: \"$(cat quote.txt)\"" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Updated CS Quote"
          git push
