name: Update README with a CS Quote

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Ensures GitHub Actions has push access

      - name: Install jq
        run: sudo apt-get install -y jq  # Install jq for JSON processing

      - name: Select a Random Quote from File
        run: |
          # Read all quotes from quotes.json and select a random one
          QUOTE=$(jq -r '. | map(.text + " - " + .author) | .[rand * length | floor]' quotes.json)
          echo "Selected Quote: $QUOTE"  # Debugging: Print the selected quote
          echo "$QUOTE" > quote.txt

      - name: Update README
        run: |
          sed -i "/<!-- CS_QUOTE -->/c\ - 💡  Computer Science Quote: \"$QUOTE\"" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Updated CS Quote" || echo "No changes to commit"
          git push
