name: Update README with a CS Quote

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Ensures GitHub Actions has push access

      - name: Install jq
        run: sudo apt-get install -y jq  # Install jq for JSON processing

      - name: Select a Random Quote from File
        run: |
          echo "Checking JSON file contents:"
          cat quotes.json  # Print the JSON file to check if it's correctly loaded

          # Count total quotes
          TOTAL_QUOTES=$(jq 'length' quotes.json)
          echo "Total Quotes: $TOTAL_QUOTES"  # Print the total number of quotes

          # Generate a random index
          RANDOM_INDEX=$((RANDOM % TOTAL_QUOTES))
          echo "Random Index Selected: $RANDOM_INDEX"  # Print the selected index

          # Select the quote at the random index
          QUOTE=$(jq -r ".[$RANDOM_INDEX].text + \" - \" + .[$RANDOM_INDEX].author" quotes.json)
          echo "Selected Quote: $QUOTE"  # Print the selected quote

          # Save quote to file
          echo "$QUOTE" > quote.txt

      - name: Update README
        run: |
          QUOTE=$(cat quote.txt)
          sed -i "/<!-- CS_QUOTE -->/c\ - 💡  Computer Science Quote: \"$QUOTE\"" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Updated CS Quote" || echo "No changes to commit"
          git push
